// Components
import Footer from './components/Footer';
import Navbar from './components/Navbar';

// Vanilla JS Scripts
import RootScripts from './script';

// CSS Libraries
import 'bootstrap/dist/css/bootstrap.min.css';
import 'aos/dist/aos.css';
import 'swiper/css';
import 'animate.css';

// AOS Initialization
import AOSInit from './components/AOSInit';

// SCSS
import '../styles/scss/main.scss';

// Main CSS
import '../../public/assets/css/default.css';
import '../../public/assets/css/default.icon.css';
import '../../public/assets/css/main.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AOSInit />
        <Navbar />
        {children}
        <Footer />
      </body>

      {/* Vanilla JS Scripts */}
      <RootScripts />
    </html>
  );
}
